#pragma once

#define VIZKEY_DEVICE_NAME "VizKey"

#define VIZKEY_BACKLIGHT_GPIO 48
#define VIZKEY_BACKLIGHT_MAX_LEVEL 255
#define VIZKEY_BACKLIGHT_OUTPUT_INVERT 0
#define VIZKEY_BACKLIGHT_DRIVER VIZKEY_BACKLIGHT_DRIVER_WS2812
#define VIZKEY_LED_ACTIVE_LEVEL 48
#define VIZKEY_LED_STANDBY_LEVEL 12

#define VIZKEY_IR_TX_GPIO 4
#define VIZKEY_IR_RX_GPIO 5

#define VIZKEY_WIFI_AP_SSID "VizKey-Setup"
#define VIZKEY_WIFI_AP_PASSWORD ""
#define VIZKEY_WIFI_AP_CHANNEL 1
#define VIZKEY_WIFI_AP_MAX_CONNECTIONS 4
#define VIZKEY_WIFI_AP_AUTO_OFF_MS 300000

#define VIZKEY_DEBUG_LED_ENABLED 1

#define VIZKEY_BLE_RECONNECT_WINDOW_MS 20000
#define VIZKEY_BLE_PAIRING_WINDOW_MS 60000
